// UUIDs are allocated once and checked in. Lesson membership never determines identity.
import fs from 'node:fs';
import {createHash, randomUUID} from 'node:crypto';
const registryFile='data/question-identities.json';
const migrationFile='app/src/main/java/com/malfreyt/alexandre/hamigo/CourseQuestionAliases47.kt';
const readRegistry=()=>fs.existsSync(registryFile)?JSON.parse(fs.readFileSync(registryFile,'utf8')):{schema:1,entries:{}};
export const authoredIdFor=(legacy)=>{const r=readRegistry();return r.bindings?.[legacy] || Object.entries(r.entries).find(([,e])=>e.legacyId===legacy)?.[0] || legacy;};
function signature(q) {
  const correct=['choice','cloze','truefalse','resistor','morseListen','waveform'].includes(q.kind)?q.choices[q.answer]:null;
  return createHash('sha256').update(JSON.stringify([q.kind,q.prompt,correct,q.value??null,q.unit??'',q.bands??[],q.pairs??[],q.kind==='order'?q.choices:[]])).digest('hex');
}
export function persistCourseQuestions(data,{bootstrap=false,dryRun=false}={}) {
  if(bootstrap && data.chapters.some(c=>c.lessons.some(l=>l.questions.some(q=>q.id.startsWith('q-')))))
    throw Error('Never bootstrap an already identified curriculum.');
  const registry=bootstrap?{schema:1,entries:{}}:readRegistry();
  registry.bindings ||= Object.fromEntries(Object.entries(registry.entries).filter(([,e])=>e.legacyId).map(([id,e])=>[e.legacyId,id]));
  for(const lesson of data.chapters.flatMap(c=>c.lessons)) for(const q of lesson.questions) {
    q.topic ||= lesson.topic;
    const fingerprint=signature(q);
    if(q.id.startsWith('q-')) {
      if(!registry.entries[q.id])throw Error('Unregistered authored UUID '+q.id);
      registry.entries[q.id].fingerprint=fingerprint;continue;
    }
    const matches=Object.entries(registry.entries).filter(([,e])=>e.fingerprint===fingerprint);
    const matchingAlias=matches.find(([,e])=>e.legacyId===q.id);
    // A unique matching exercise keeps its UUID even after moving or changing course order.
    let id=bootstrap?null:(matchingAlias?.[0] || (matches.length===1?matches[0][0]:null));
    if(!id) {
      if(!bootstrap && matches.length>1)throw Error('Ambiguous exercise: supply its explicit q-UUID. '+q.prompt);
      id='q-'+randomUUID();registry.entries[id]={legacyId:bootstrap?q.id:'',fingerprint};
    }
    registry.bindings[q.id]=id;q.id=id;
  }
  const questions=data.chapters.flatMap(c=>c.lessons.flatMap(l=>l.questions));
  if(new Set(questions.map(q=>q.id)).size!==questions.length)throw Error('Duplicate authored UUID');
  if(dryRun)return questions;
  fs.writeFileSync(registryFile,JSON.stringify(registry,null,2)+'\n');
  const curriculum=structuredClone(data);
  for(const l of curriculum.chapters.flatMap(c=>c.lessons)) {l.questionIds=l.questions.map(q=>q.id);delete l.questions;}
  const bank=JSON.stringify({schema:1,questions},null,2)+'\n';
  fs.writeFileSync('data/course-questions.json',bank);
  fs.writeFileSync('app/src/main/assets/course-questions.json',bank);
  fs.writeFileSync('data/curriculum.json',JSON.stringify(data,null,2)+'\n');
  fs.writeFileSync('app/src/main/assets/curriculum.json',JSON.stringify(curriculum,null,2)+'\n');
  // Temporary runtime compatibility is independent of the permanent authoring registry.
  // At 0.52 remove this file and CourseQuestionMigration47, never regenerate shipped UUIDs.
  const aliases=Object.entries(registry.entries).filter(([,e])=>/^c\d+-l\d+-q\d+$/.test(e.legacyId));
  const source='package com.malfreyt.alexandre.hamigo\n\n// Generated by question_identities.mjs. REMOVE WITH MIGRATION AT 0.52.\ninternal object CourseQuestionAliases47 {\n    val ids: Map<String,String> = mapOf(\n'+aliases.map(([id,e])=>'        "'+e.legacyId+'" to "'+id+'"').join(',\n')+'\n    )\n}\n';
  fs.writeFileSync(migrationFile,source);
  return questions;
}
