import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {persistCourseQuestions} from './question_identities.mjs';
const paths=['data/curriculum.json','data/course-questions.json','data/question-identities.json','app/src/main/assets/curriculum.json','app/src/main/assets/course-questions.json','app/src/main/java/com/malfreyt/alexandre/hamigo/CourseQuestionAliases47.kt'];
const digest=()=>paths.map(p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex'));
const before=digest();
execFileSync(process.execPath,['tools/expand_curriculum.mjs']);
assert.deepEqual(digest(),before,'Regeneration must not replace shipped UUIDs or change content');
const data=JSON.parse(fs.readFileSync(paths[0],'utf8'));
const ids=data.chapters.flatMap(c=>c.lessons.flatMap(l=>l.questions.map(q=>q.id))).sort();
data.chapters.reverse();data.chapters.forEach(c=>{c.lessons.reverse();c.lessons.forEach(l=>l.questions.reverse());});
data.chapters[0].lessons[0].questions.push(data.chapters[1].lessons[0].questions.pop());
const moved=persistCourseQuestions(data,{dryRun:true}).map(q=>q.id).sort();
assert.deepEqual(moved,ids,'Moving a question or reordering the path must not change its identity');
assert.deepEqual(digest(),before,'The dry-run fixture must not modify authoring files');
const aliases=JSON.parse(fs.readFileSync('data/question-identities.json','utf8')).entries;
assert.equal(Object.values(aliases).filter(e=>e.legacyId).length,850);
assert.equal(new Set(Object.values(aliases).filter(e=>e.legacyId).map(e=>e.legacyId)).size,850);
console.log('842 active UUIDs, 850 unique historical aliases; deterministic regeneration and move/reorder checks passed.');
